name: Build and deploy to gh-pages

on:
    push:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 6.32.3
            - name: Use Node.js v16
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build site
              run: node index.js
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4.3.0
              with:
                  branch: gh-pages
                  folder: data
